// data.js
// Stores syllabus, question bank, and localized strings

window.DSE_MATH_DATA = {
  // Bilingual translations
  i18n: {
    en: {
      title: "HKDSE Mathematics Exercise Generator",
      subject: "Subject",
      topic: "Topic",
      paper: "Paper",
      difficulty: "Difficulty",
      level: "Level",
      levels: {
        A1: { label: "Level A1 (Basic)", desc: "Basic topics only, direct calculation, no cross-topics, 1-2 steps to complete." },
        A2: { label: "Level A2 (Standard)", desc: "Includes non-basic content, conceptual links, requires steps/reasoning, 3-5 steps." },
        B: { label: "Level B (Advanced)", desc: "Combines multiple topics, 3D contexts or complex real-world applications, requires analysis and synthesis." }
      },
      generateBtn: "Generate Question",
      hint: "Show Hint",
      steps: "Show Answer & Steps",
      correctMsg: "Correct!",
      wrongMsg: "Incorrect, try again.",
      paper1: "Paper 1 (Long/Short Qs)",
      paper2: "Paper 2 (Multiple Choice)",
      selectTopic: "-- Select a Topic --",
      generating: "Generating...",
      errorGenerative: "Error generating question. Check API Key or try again.",
      topics: {
        compulsory: [
          "Quadratic Equations in One Unknown",
          "Functions and their Graphs",
          "Exponential and Logarithmic Functions",
          "More about Polynomials",
          "More about Equations",
          "Variations",
          "Arithmetic and Geometric Sequences and their Summation",
          "Inequalities and Linear Programming",
          "More about Graphs of Functions",
          "Basic Properties of Circles",
          "Loci",
          "Equations of Straight Lines and Circles",
          "More about Trigonometry",
          "Permutation and Combination",
          "More about Probability",
          "Measures of Dispersion",
          "Uses and Abuses of Statistics",
          "Further Applications of Mathematics",
          "Inquiry and Investigation"
        ],
        m1: [
          "Binomial Expansion",
          "Exponential and Logarithmic Functions",
          "Derivatives of Functions",
          "Differentiation of Functions",
          "Second Derivatives",
          "Applications of Differentiation",
          "Indefinite Integrals and their Applications",
          "Definite Integrals and their Applications",
          "Approximating Definite Integrals using Trapezoidal Rule",
          "Conditional Probability and Independence",
          "Bayes' Theorem",
          "Discrete Random Variables",
          "Probability Distributions, Expectation and Variance",
          "Binomial Distribution",
          "Geometric Distribution",
          "Poisson Distribution",
          "Applications of Binomial, Geometric and Poisson Distributions",
          "Basic Definitions and Properties of Normal Distribution",
          "Standardisation of Normal Variables",
          "Applications of Normal Distribution",
          "Sampling Distributions and Point Estimation",
          "Confidence Intervals for Population Mean",
          "Confidence Intervals for Population Proportion"
        ],
        m2: [
          "Surds",
          "Mathematical Induction",
          "Binomial Theorem",
          "More about Trigonometric Functions",
          "Introduction to e",
          "Limits",
          "Differentiation",
          "Applications of Differentiation",
          "Indefinite Integration",
          "Definite Integration",
          "Applications of Definite Integration",
          "Determinants",
          "Matrices",
          "Systems of Linear Equations",
          "Introduction to Vectors",
          "Scalar Product and Vector Product",
          "Applications of Vectors"
        ]
      }
    },
    zh: {
      title: "香港DSE數學科練習題生成器",
      subject: "學科",
      topic: "課題",
      paper: "試卷",
      difficulty: "難度",
      level: "等級",
      levels: {
        A1: { label: "Level A1 (基礎)", desc: "僅限基礎課題，直接運算，無須跨課題，1-2 步完成。" },
        A2: { label: "Level A2 (標準)", desc: "包含非基礎內容，涉及概念聯繫，須書寫步驟或理由，步驟約 3-5 步。" },
        B: { label: "Level B (進階)", desc: "綜合多個課題，包含三維情境或複雜現實應用題，要求分析與綜合能力。" }
      },
      generateBtn: "生成題目",
      hint: "顯示提示",
      steps: "顯示答案及運算步驟",
      correctMsg: "正確！",
      wrongMsg: "錯誤，請再試一次。",
      paper1: "卷一 (長/短題目)",
      paper2: "卷二 (多項選擇題)",
      selectTopic: "-- 請選擇課題 --",
      generating: "生成中...",
      errorGenerative: "生成題目失敗，請檢查 API Key 或稍後再試。",
      topics: {
        compulsory: [
          "一元二次方程",
          "函數及其圖像",
          "指數函數與對數函數",
          "續多項式",
          "續方程",
          "變分",
          "等差數列與等比數列及其求和法",
          "不等式與線性規畫",
          "續函數圖像",
          "圓的基本性質",
          "軌跡",
          "直線與圓的方程",
          "續三角",
          "排列與組合",
          "續概率",
          "離差的度量",
          "統計的應用及誤用",
          "數學的進一步應用",
          "探索與研究"
        ],
        m1: [
          "二項展式",
          "指數函數及對數函數",
          "函數的導數",
          "函數的求導法",
          "二階導數",
          "求導法的應用",
          "不定積分及其應用",
          "定積分及其應用",
          "使用梯形法則計算定積分的近似值",
          "條件概率和獨立性",
          "貝葉斯定理",
          "離散隨機變量",
          "概率分佈, 期望值和方差",
          "二項分佈",
          "幾何分佈",
          "泊松分佈",
          "二項、幾何和泊松分佈的應用",
          "基本定義及其性質（正態分佈）",
          "正態變量的標準化及標準正態分佈表的使用",
          "正態分佈的應用",
          "抽樣分佈和點估計",
          "總體平均值的置信區間",
          "總體比例的置信區間"
        ],
        m2: [
          "根式",
          "數學歸納法",
          "二項式定理",
          "續三角函數",
          "e 的簡介",
          "極限",
          "求導法",
          "求導法的應用",
          "不定積分法",
          "定積分法",
          "定積分法的應用",
          "行列式",
          "矩陣",
          "線性方程組",
          "向量的簡介",
          "純量積與向量積",
          "向量的應用"
        ]
      }
    }
  },

  subjects: [
    { id: 'compulsory', labelEn: 'Compulsory Part', labelZh: '必修部分' },
    { id: 'm1', labelEn: 'Module 1 (M1)', labelZh: '單元一 (M1)' },
    { id: 'm2', labelEn: 'Module 2 (M2)', labelZh: '單元二 (M2)' }
  ]
};
